# Generated by Django 5.2.9 on 2025-12-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ouvrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=255)),
                ('editeur', models.CharField(blank=True, max_length=255, null=True)),
                ('annee', models.PositiveIntegerField(blank=True, null=True)),
                ('categorie', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
