# Generated by ChatGPT on 2025-02-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ouvrages", "0003_demandes_ebooks"),
    ]

    operations = [
        migrations.AddField(
            model_name="ouvrage",
            name="description_courte",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ouvrage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="ouvrages/"),
        ),
    ]
