# Generated by Django 5.2.9 on 2025-12-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_penalite_par_jour', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('duree_emprunt_jours', models.PositiveIntegerField(default=14)),
                ('quota_emprunts_actifs', models.PositiveIntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
