# Generated by Django 5.2.7 on 2025-12-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('EMPRUNT_CREE', 'Emprunt cree'), ('RETOUR_ENREGISTRE', 'Retour enregistre'), ('PENALITE_CREE', 'Penalite creee'), ('PENALITE_PAYEE', 'Penalite payee'), ('OUVRAGE_AJOUTE', 'Ouvrage ajoute'), ('EXEMPLAIRE_AJOUTE', 'Exemplaire ajoute'), ('USER_CREATED', 'Utilisateur cree'), ('USER_UPDATED', 'Utilisateur modifie'), ('USER_DISABLED', 'Utilisateur desactive'), ('PASSWORD_RESET', 'Mot de passe reinitialise')], max_length=40),
        ),
    ]
