# Generated by Django 5.2.9 on 2025-12-26 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ouvrages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_barre', models.CharField(max_length=50, unique=True)),
                ('etat', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EMPRUNTE', 'Emprunté'), ('PERDU', 'Perdu'), ('ENDOMMAGE', 'Endommagé')], default='DISPONIBLE', max_length=20)),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplaires', to='ouvrages.ouvrage')),
            ],
        ),
    ]
