# Generated by Django 5.2.9 on 2025-12-26 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherents', '0001_initial'),
        ('exemplaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(auto_now_add=True)),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_effective', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('RETOURNE', 'Retourné'), ('EN_RETARD', 'En retard')], default='EN_COURS', max_length=20)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprunts', to='adherents.adherent')),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprunts', to='exemplaires.exemplaire')),
            ],
        ),
    ]
