# Generated by Django 5.2.9 on 2025-12-26 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jours_retard', models.PositiveIntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payee', models.BooleanField(default=False)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('emprunt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='penalite', to='emprunts.emprunt')),
            ],
        ),
    ]
