# Generated by Django 5.2.7 on 2025-12-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0004_reservation_dates_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='montant_estime',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
